server:
  port: 8081

spring:
  application:
    name: building-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/building_service_db
    username: postgres
    password: root
    pool:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/building_service_db
    user: postgres
    password: root
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS}  %-5level --- [%X{spanId} | %thread] %logger{0} : %msg%n'
  level:
    root: DEBUG
    org.liquibase: DEBUG
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    use-root-path: true
