server:
  port: 8082

spring:
  application:
    name: inventory-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/inventory_service_db
    username: postgres
    password: root
  liquibase:
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/inventory_service_db
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
#    enabled: false
logging:
  level:
    org.liquibase: DEBUG
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    use-root-path: true